// Learning Unit (Bilibili Video unit added by Parent or preset)
export interface BiliVideo {
  id: string; // unique ID
  title: string;
  description: string;
  pic?: string; // thumbnail
  duration?: number; // in seconds
  owner?: string; // UP name
  category: "chinese" | "math" | "english" | "physics" | "chemistry" | "biology" | "other" | "mechanics" | "optics" | "acoustics" | "thermal" | "electromagnetics";
  bvid: string; // BV physical string
  videoUrl: string;
  gradeLevel: string; // e.g. "初中一年级", "初中二年级", "初中三年级", "小学科学"
  addedAt: string;
  quizGenerated: boolean;
  quizData?: QuizData;
  readingMaterial?: ReadingMaterial;
  parts?: BiliVideoPart[]; // Optional list of episodes/chapters if it's a series video
}

export interface BiliVideoPart {
  page: number; // 1-indexed part number used in Bilibili URL (?p=X)
  title: string; // part/episode subtitle
  duration?: number;
  quizGenerated: boolean;
  quizData?: QuizData;
  readingMaterial?: ReadingMaterial;
}

export interface ReadingMaterial {
  title: string;
  content: string; // supports Markdown formats
  funFacts: string[]; // List of 3-4 fun physics facts
  suggestedActivity: string; // Hands-on mini-experiment
}

// Full Quiz metadata generated by Gemini
export interface QuizData {
  topicSummary: string; // 150-word quick recap
  keyFormulas: KeyFormula[]; // Important physics formulas involved
  questions: QuizQuestion[];
}

// Single multi-choice question
export interface QuizQuestion {
  id: number;
  question: string;
  options: string[]; // 4 parts (A, B, C, D)
  correctAnswer: number; // index (0-3)
  difficulty: "basic" | "intermediate" | "challenging";
  explanation: string; // Rich detailed teacher text explanation
  hint: string; // Clue helper
}

// Key Formulas structure
export interface KeyFormula {
  name: string;
  expression: string;
  unit: string;
  desc: string;
}

// Child's actual test submission history
export interface StudyRecord {
  id: string;
  videoId: string;
  videoTitle: string;
  score: number; // e.g. 80, 100
  totalQuestions: number;
  correctCount: number;
  completedAt: string;
  answers: { [questionId: number]: number }; // questionId -> selectedOptionIdx (-1 for skipped)
}

// Gamification: Medals earned by child
export interface Medal {
  id: string;
  title: string;
  description: string;
  icon: string; // lucide icon identifier
  color: string; // CSS color string (bg-theme, text-theme)
  unlockedAt?: string;
}

// Physics Formulas categories for Formula Sheet helper
export interface SandboxFormula {
  id: string;
  name: string;
  expression: string;
  inputs: { key: string; name: string; unit: string; symbol: string }[];
  calculate: (values: { [key: string]: number }) => { result: number; formulaSteps: string; unit: string };
}
